### PR TITLE
Add region restriction

### PR DESCRIPTION
**Pull request by zakdoek**
Allow for plugin restriction per region.

```
class MyPlugin(PluginBase):
    class Meta:
        regions = ("region_1_key", "region_2_key")
```

When the region field is not set, a plugin can be added to all regions.

### CODE REVIEW

**Comment by matthiask** [comment]
Thank you! I worry a bit about extending the Meta options, but it will probably be fine. I can't see any server side validation of regions - do you think it would make sense to add this as well?

**Comment by matthiask** [comment]
Plugin buttons will still be visible.

screen shot 2016-09-06 at 08 42 00

**Comment by zakdoek** [comment]
I gave it some thought about the meta options and it would make sense to move the restrict_regions to the ContentEditorInline instance under the `regions` keyword much alike the `filter_horizontal`since the option only affects admin ui.

Server side validation would make sense when the `regions` key would have changed in between versions. The user would be prompted and forced to "clean up" the model instance. But a case like that should ideally be nonexistent since this should by handled by a data migration. Also i do not consider the django admin suited for public exposure.

I did forget about the plugin buttons but this should be quickly fixed.

If this sounds good to you, i will implement these changes. What do you think about the proposed changes?

**Comment by matthiask** [comment]
Well, restricting plugins to regions was available in FeinCMS as well, so I'll happily merge these changes! The implementation in FeinCMS was not complete though — it allowed adding plugins, and moving them into regions where they shouldn't be, therefore my question regarding server side validation. 

If `regions` is a model-level attribute it should be validated. I like your proposal of moving `regions` to the `ContentEditorInline` it's more of a presentation thing then, and if someone really wants to circumvent this then more power to them.

**Comment by zakdoek** [comment]
Ok. I will modify my patch and push shortly.

**Comment by zakdoek** [comment]
Done. Plugin restriction is now set through the ContentEditorInline instance.

**Comment by matthiask** [comment]
Thank you! Looks good.

**Comment by matthiask** [comment]
Merged, and added docs in 38a8befdd992cc2909ae07f73f707e36b218de9b.

**Pull request merged**
